### PR TITLE
Update styles.css

### PR DESCRIPTION
**Pull request by zipage**
I will use this file to update my css

### CODE REVIEW

**Comment by zipage** [comment]
Screenshot (23)

Alright! I think I have gotten it! 
I'm still learning how to implement BEM but I think(??) I have it mostly correct. I will study more of BEM and see if I can apply it to either this project or another one. Please let me know if my code looks alright or if there needs to be addition changes.

**Comment by zipage** [comment]
@jonspark so I am overall understand how BEM is to be integrated into CSS. However, 

1. I have no idea how I would approach naming the elements and mods in the css. 

My other question was 

2. In what areas is it beneficial to use BEM in CSS versus just using vanilla CSS? 

I watch a few videos and read the CSS BEM link you emailed as well as a few others, I am jus unsure how I approach naming.

**Comment by jonspark** [comment]
It's looking good Zí, well done!

> 1. I have no idea how I would approach naming the elements and mods in the css.

The best way to name components/Blocks is to think about what they describe by their content. If I was approaching this task, I might break it up like so:

components

- The black box looks like a page header to me, so that could just be `.Header`
- The top blue-y, purple box is part of the header, but specific to navigation. That's important enough for its own Block, so we could go with `.Navigation`
- The blue box around Justine's information describe their user profile. I could see there being modifiers for this elsewhere in the app, so I'd lean away from `.Profile` and call it `.User` instead.
- The gold box around the curved background is probably two components. The main content, which we could leave class-less and use the `<main>` tag, and a `.BookList`.
- Lastly, each image and title inside of `.BookList` could be its own `.Book` block. Again, this could show up elsewhere in the app.

> 2. In what areas is it beneficial to use BEM in CSS versus just using vanilla CSS?

I would say most areas, if not almost all. Even if you're not using a component-based JavaScript framework like React or Vue, just from an organisation standpoint, it makes your code a lot neater.

The worst case in Vanilla CSS is having to add lots of `!important`s to prevent styles cascading that you don't want.

The example is a little trivial, but this variant of the user information would use the same HTML but with one added modifier class.

Screenshot 2020-10-30 at 10 38 43

There's a lot of focus on Design Systems at the moment and those usually incorporate some kind of UI Kit. For big organisations, it makes sense for them to have a unified design across all aspects of their business. It's a bit daft having developers code the same thing over and over again, so most maintain a library.

I like to do this too. Even if it's not formalised into a documented site, I'll work as if I were. Where I can, I put a UI kit together for clients to start building their own design systems. When I'm working with junior developers, it can be very helpful for them to focus on this whilst I'm working on databases or integrating React.

I hope this helps. I'm here if you have any questions or need any pointers.

**Comment by zipage** [comment]
@jonspark  Okai so I am working through implementing BEM as you suggestion, but I have no idea if I am doing this correctly or if I am ding this backwards. Before spending a long time, I wanted to just clarify with you if I am in the right direction or not.  Here is my code examples;
[
Screenshot (24)
](url)
**BEM CSS:** 

` html, body {
    margin: 0;
    padding: 0;
 }

 .header .header__navigation1 {
    float: left;
    display: inline;
    padding: 35px; 
 }

 .header .header__navigation2 {
    float: right;
    display: inline;
    float: right;
    display: inline;
    padding: 35px; 
 } `

**Comment by jonspark** [comment]
You wouldn't apply `.header` to each child element. That's where the "E" part of BEM comes in.

```html
<div class="header">
  <div class="header__inner">
    <img class="header__arrow" />
    <div class="header__profile>
      <!-- All the other bits -->
     </div>
  </div>
</div>
```

**Comment by zipage** [comment]
@jonspark ohh okai thank goodness! I was thinking " man this is a lot of redundant code" LOL! 
I will work at updating the rest of the CSS with BEM and hopefully I won't run into anymore confusions or issues until I finish it and then I will show you after! thanks

**Comment by zipage** [comment]
@jonspark If I get excited thinking about code and/or dreaming about figuring a code issue, does that officially make me web dev yet??😂

So I've been working through with the BEM and I'm pretty exited! I think(??) I have done it correctly??

I will post my code later tonight or tomorrow, I just havent had access to a bigger screen/monitor this weekend. 

I am making myself add more comments for myself to stay organized and hopefully, it allows my code more readable. 

Im excited to show you my updated code and I hope I did it correct or at least I'm on the right path.

**Comment by jonspark** [comment]
You're certainly on your way! Let me know when you'd like me to review something 🙂

**Comment by zipage** [comment]
Screenshot (25)

Okai! this is my updated CSS & HTML with BEM now implemented.
For some reason the text in the first book isn't lined up properly like the other ones and I tried to figure it out for a while, but I am unsure how to fix that issue. Other than that I hopeee it looks okai!

**Comment by jonspark** [comment]
Cool. You're pretty-well BEM-ed up.

Let's merge all your changes to the main branch and then see what we can improve next. Perhaps we could focus on the BookList seeing as you've mentioned the text alignment.

A good branch name could be `enhancement/book-list` (I only prefer to structure them this way because Git GUIs tend to turn them into folders), and a good PR title might be "Improving book display".

If you'd rather look at something else that's cool, just use those suggestions as a basis.

**Comment by zipage** [comment]
@jonspark ill do that right now😁

**Pull request merged**
